### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by pcnate** [EricSmekens/node-bluetooth-obd#32]
Upon installation on raspbian the following error occurs
```
pi@raspi-car-01:~/testodb2 $ npm install --save bluetooth-obd

> bluetooth-serial-port@2.1.7 install /home/pi/testodb2/node_modules/bluetooth-serial-port
> node-gyp configure build

make: Entering directory '/home/pi/testodb2/node_modules/bluetooth-serial-port/build'
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o
../src/linux/DeviceINQ.cc:35:37: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
                                     ^
compilation terminated.
BluetoothSerialPort.target.mk:105: recipe for target 'Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o' failed
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o] Error 1
make: Leaving directory '/home/pi/testodb2/node_modules/bluetooth-serial-port/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.79+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/testodb2/node_modules/bluetooth-serial-port
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Please add to the installation that `libbluetooth-dev` is required as found on [stackoverflow.com](https://stackoverflow.com/a/23442501/3851647)

**Comment by pcnate** [comment]
Apparently I cannot read
